### ISSUE TITLE
Proposal | Wind down SynthVault Harvest Percentage

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanswap-contracts#105]
As we all knew with the leadup to V2, Synths require significant TVL to thrive & have any chance of ontop-layer features being available to them. They were probably enabled too early before TVL had a chance to grow and therefore are not bringing benefits to the protocol paired with current TVLs.

I propose we turn off synth minting (it basically already is, as we are at the caps most/all of the time) and dial down the Synth-harvest percentage over the next few months, maybe 1% every 2 weeks or thereabouts until we hit 0%, effectively pushing people to gradually burn their synths. Synth stakers (myself included) have been reaping the benefits of harvesting synths with almost zero weight growth to compete with for probably a month now, so any burning fees and rate slips will be well and truly paid forward already, but in the event this proposal is agreed with and followed through on, there will also be no rush for anyone to exit straight away, the whole point would be to gradually reduce incentives and allow people to burn in their own time so that it doesn't instead happen suddenly one day if there are v3 pools to migrate to.

This may sound like a dramatic move, but at the current TVL, we are only talking about ~$300k worth of synths with no extra room for them to grow unless the TVL increases at a wild rate suddenly.

Separate, but worth mentioning now: i would like to devote the majority of my time after the DApp & websites are revamped to work with the community on a possible efficiency upgrade to the pools (pools v3) and if such a project reached mainnet completion, would require the v2 pools be disbanded and liquidity migrated to the v3 pools. The order of operations is for synths to burn well before the liquidity does, so it also makes sense from this perspective to wind down synths and have Spartans migrate out in a responsible manner leaving us with a much more simple possible migration if it so happens later down the track.

Over the past 6 months or so there have been many things as usual being worked on by the smart contract contributors and wider community in the form of ideas too.
One of those is a CDP protocol stablecoin, which I believe would require a shakeup of the current synthetic design and maybe a sole focus on synthetic stablecoins instead of synth versions of all curated tokens. Therefore best to build such an item whist we have an opportunity to adjust the pools and synths design to suit it

There are existing contributors who have shown interest to work on v3 pools + stablecoin and help teach me along the way, along with some newer contributors who want to join in on the contracts side too, so focus there would be great, winding down synths would be a great step towards that

Lending is unaffected by the pools changing, as any typical lending implementation is its own protocol that would be agnostic to what goes on with the main protocol anyway, so any contributors working on different forms of lending need not be worried, but please reach out if you have any objections or worries. Worth noting that the CDP stablecoin would most likely be a form of lending in itself anyway so there may be some opportunities or ideas that other contributors can bring across and combine or empower through these opportunities

Anyway, these are my thoughts of late, looking forward to some unbiased feedback from the community, please!

Also, important to note, that I am just a community member like the rest, the above are my thoughts/wants and I don't necessarily have the power to make them happen, can only propose and see what comes of it. I can't promise a V3 pools or decentralised protocol synthetic stablecoin (v2 synths) get built and/or make it to mainnet, however, I do promise ill devote time to round up community contributors and explore these ideas as a possible next stage for the protocol.

Community & Contributors:
• Please contribute to this discussion even if you are not a contributor, my above words are my own, they aren't the project's opinion, we form that collectively, not as any one individual
• But I understand there are alot of Spartans, especially the main contributors, who value privacy above all else and would rather PM me, if that's the case please do so and I'll make sure your piece is shared in an anonymous way

**Comment by SamusElderg** [comment]
@verifyfirst if you could weigh in with input after discussing with each other pls ❤️

**Comment by SamusElderg** [comment]
@jejopl would love to have you come get involved in the contracts after we get the dapp + website up to scratch, good way to get your solidity beak wet 🐦💧

**Comment by SamusElderg** [comment]
@jacobostel your input would be valued too!
I can't find anyone else's Github usernames so ill ping you on Telegram 😂

**Comment by crypticalcrypto** [comment]
I am all for switching up and kicking on with the proposed upgrades. We have already discussed and I think a stablecoin is a good next step in our evolution. It's no secret that the current TVL is not where we would like after we lost a lot of momentum while V2 was being built. Would be good to freshen things up and not just sit back and hope the TVL will organically grow and synths become more relevant in the future. Developing a new and interesting feature is a great way to keep the protocol relevant and competing with all the new projects around in my opinion. Ps I would still like to see a lending product too 😀

**Comment by verifythestack** [comment]
Well written and considered
Turns out that synths wasn’t the thing people were clambering for. I’ve got some in there, but interested in long term value add to project. 

A simple upgrade to v3 and a stable seems to be what we need to move forward. 

It has my support :). Thanks for proposing

**Comment by verifyfirst** [comment]
@SamusElderg appreciate the ping and the proposal.

The current V2 synths design was a heavy weighted milestone taking many iterations and attempts to achieve a sustainable product for the Spartan ecosystem. The contributors/members of the community shouldered the difficulty and pressure of implementing such a feature, following the unfortunate attack in May 2021. 

This proposal is unsurprising given the outcome and current TVL circumstances hindering the growth of protocol/synths. The implemented synths design relied upon deep liquidity for its success and to limit possible economic attack vectors. Unfortunately, the protocol has struggled to achieve its desired TVL levels and thus the synths design isn't delivering much utility to the protocol.

Although the synths were unable to rise to their intended glory, Spartan Protocol has been developed to forever evolve via a systematic loop sequence of Build, Test, Analyse and Revise. The outcome achieved from the synths design can now be used to bring forth a revised synthetics feature as outlined @SamusElderg. 

The direction forward is clear.

**Comment by justjack1** [comment]
Fully agree...let's move forward with a streamlined protocol and hopefully our own stablecoin which could maybe enable lending too. Onwards and upwards Spartans!

**Comment by jacobostel** [comment]
Sounds great, a project in constant evolution is key to bring the protocol further... Aroo!!

**Comment by jejopl** [comment]
Sounds good! 
![image](https://user-images.githubusercontent.com/32012330/163215602-b9da882e-1d11-45cc-9440-9dcfd40290ee.png)

**Comment by moneymanagement** [comment]
Sounds good, I'm in for any steady progress.

**Comment by bitdingus** [comment]
Agreed, Synths in the current state of TVL are in severe need to be wound down if we value sustainability and proportionate incentives, and their current design should only really be enabled for minting if TVL pops over $100M and holds there for some months. The current synths design is good, but very, very TVL hungry. Redesigning Synths with a focus on a synthetic stablecoin + not capped by a portion of a subsection of the TVL and other limitations would be much better than waiting for $100M TVL... so your extended comments sound like a better plan than waiting + hoping. 

I think a single synthetic decentralised stablecoin sUSD/USDS/SynthUSD/SPUSD or whatever we might call it is much more powerful even on its own than limited synthetic versions of the assets we already have on BNBChain. And a stablecoin is how we can determine leverage in one direction or the other among many other things, so technically having one synth (if its a stablecoin) enables a lot of the previously wanted 'synth features' in all of pools that the current design would only possibly allow in Curated pools. Probably with less required TVL too.

I have some ideas for what I suspect is this kind of stablecoin design and I am glad Spartans seem to be leaning towards a more stable, non-algo style... stable (CDP is good especially if collateralised by LPs in some way) as this suits a lot of similar my ideas mulling over recently with the brain juice being fuelled by recent stable hype

I by no means am an expert in smart contracts, however I do have a couple years exposure to solidity & defi SCs in general and could be of value, I'll put my hand up to help with system design/theory, testing/attack vector sims and smart contract writing. I dont know the correct terms for those phases but you get the idea. And will do my best to help with front end along the way too. 

For those who don't know, I have contributed in the past in a variety of ways but not very publicly, ill try my best to get out of my comfort zone and change that from now on, I even made a GitHub account haha, look at me go!

**Comment by SamusElderg** [comment]
> Sounds good! 
> ![image](https://user-images.githubusercontent.com/32012330/163215602-b9da882e-1d11-45cc-9440-9dcfd40290ee.png)
> 

![images (8).jpeg](https://user-images.githubusercontent.com/26967164/163492160-e17d2336-8e6d-49b4-9c9c-ee21d01f12f2.jpeg)

**Comment by Aj2083** [comment]
I am very pleased with this proposal and from reading all above comments regarding why this would benefit Spartan Protocol.. I am even more excited for our future.. we have such a great community filled with great minds from the crypto/blockchain/smartcontract/DeFi industry and I am so proud to be a part of this... our future is strong.. I have wanted a stable coin for Sparta for the longest and lending of course, this is our next leg up... Go SPARTA!!! SPARTA 4 LIFE...
