### ISSUE TITLE
ADD: Mint+Lock

### ISSUE THREAD

**Issue by spartan-admin** [spartan-protocol/spartanswap-contracts#33]
# Spec

- A user can deposit an amount (let's say $1k) in a whitelisted asset (i.e. BNB)
- $1k of SPARTA tokens (at the current pool price) are minted into circulation.
- Both the $1k in BNB (deposited by user) and $1k in SPARTA (minted by contract) are moved into the BNB:SPARTA liquidity pool.
- Equivalent units of the LP tokens are issued and sent to lock contract.

The community & smart contract devs are in discussions about these ratios, but for instance:
- 25% of these LP tokens are then immediately sent back to the owner.
- The other 75% of the LP tokens are vested linearly back to the owner on a continuous per-second basis over 12 months (31,536,000 seconds)

# Implementation

## LOCK Contract is BEP-20

In order to get an allocation of SPARTA, the lock contract must generate an BEP-20 that is then whitelisted into the SPARTA contract as a burnable asset. The amount of SPARTA emitted can be set by the burn ratio. 

The LOCK contract then "burns" and SPARTA will then mint and issue back an allocation of SPARTA, eg, 5m SPARTA. The LOCK contract now owns 5m SPARTA in order to allow users to LOCK. 

### Constructor
* Create BEP-20 of fixed supply, eg 1, then mint to `address(this)`

### burn()
* When LOCK-TOKEN is whitelisted in SPARTA, anyone can call `burn()` to burn 1 unit into SPARTA, and for it to issue back the allocation of new supply

### deposit()
* Any user can then `deposit(asset, amount)` which then gives them an allocation of the SPARTA supply, which is priced by the current spartan-pool price for that asset
* The BNB + SPARTA is then `addLiquidity()` into the ROUTER
* LP tokens are issued and sent back
* 50% given back to `msg.sender`
* 50% then goes into a mapping for that user, saving the current time `now`

### claim()
* User with non-zero LP token balance can call claim which then looks at how many `secondsSinceLastClaim`
* The number of seconds * vesting rate is the claimable balance
* `secondsSinceLastClaim` are reset
* balance is then sent to the user

# Contracts

1) Sparta (base)
2) LOCK-TOKEN
3) DAO (to whitelist (2) in (1)
4) BNB or other Asset (BEP-20) for locking
5) ROUTER && POOL (for adding liquidity)
6) Utils (for pricing)

**Comment by spartan-admin** [comment]
Suggest looking at the current tests for this repo, eg, `4_dao,js` to find a good starting place that already implements the bulk of the above.

**Comment by verifyfirst** [comment]
#36 closes #33

**Comment by verifyfirst** [comment]
Closed by #36
