### ISSUE TITLE
DAO V2 | Create automated testing for weight & isMember

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanswap-contracts#45]
• Ensure wallet is removed as isMember when tokens are unlocked from DAO

• Ensure forced harvest with all weight change txns

• Ensure members weight is remapped with all weight changing txns 

Scenario:
• Create multiple wallets, add small liquidity with each wallet and lock in DAO (to make you isMember)
• Create a 'main' wallet and add main assets to all pools and lock LP tokens in the DAO
• Wait a month or so
• Claim harvest in main wallet, then send the LP Tokens to each wallet, rinse/repeat

**Comment by verifyfirst** [comment]
#49
